name: Code-Coverage Report

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: write-all
    name: CI analyze
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Install obligatory dependencies
        run: pip3 install -r requirements.txt

      - name: Install pytest
        run: pip3 install pytest
      
      - name: Install coverage
        run: pip3 install coverage

      - name: Add temporary PYTHONPATH and run coverage
        run: PYTHONPATH=lib coverage run -m pytest tests/

      - name: Convert coverage report to XML format
        run: coverage xml

      - name: Run Codecov-Action
        uses: codecov/codecov-action@v2
        with:
          token: ${{ github.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true